version: '3.7'

volumes:
  pi_hole_conf:
    name: pi_hole_conf
  pi_hole_dnsmasq:
    name: pi_hole_dnsmasq

networks:
  pi_hole_net:
    name: pi_hole_net

services:
  pihole:
    image: pihole/pihole:$TAG
    container_name: pihole
    environment:
      - TZ=$TZ
      - WEBPASSWORD=$WEBPASSWORD
      - FTLCONF_LOCAL_IPV4=$FTLCONF_LOCAL_IPV4
      - PIHOLE_DNS_=$PIHOLE_DNS
      - DNSSEC=$DNSSEC
      - VIRTUAL_HOST=$VIRTUAL_HOST
      - TEMPERATUREUNIT=$TEMPERATUREUNIT
    ports: 
      - $DNS_INTERFACE_BIND:$DNS_PORT:53/tcp
      - $DNS_INTERFACE_BIND:$DNS_PORT:53/udp
      - $HTTP_INTERFACE_BIND:$HTTP_PORT:80/tcp
      - $HTTP_INTERFACE_BIND:$HTTPS_PORT:443/tcp
    volumes:
      - pi_hole_conf:/etc/pihole
      - pi_hole_dnsmasq:/etc/dnsmasq.d
    networks:
      - pi_hole_net
    restart: always