pipeline {
	agent {
		docker {
			image 'docker:latest'
			args '-v /var/run/docker.sock:/var/run/docker.sock'
		}
	}
	options {
		ansiColor('xterm')
	}
	environment {
    SERVICE = "pi-hole"
    VERSION = "latest"
    PIHOLE_DOMAIN = credentials("pihole-domain")
    TZ = "Europe/London"
    WEBPASSWORD = credentials("pihole-web-password")
    FTLCONF_LOCAL_IPV4 = "0.0.0.0"
    PIHOLE_DNS = "1.1.1.1;1.0.0.1"
    DNSSEC = true
    VIRTUAL_HOST = credentials("pihole-public-host-name")
    TEMPERATUREUNIT = "c"
		DNSMASQ_LISTENING = "all"
    DNS_INTERFACE_BIND = "0.0.0.0"
    DNS_PORT = 53
		DVB_VERSION = "2.6.0"
		DOCKER_SOCKET = "/var/run/docker.sock"
		AWS_S3_BUCKET_NAME = credentials("docker-volume-backup-bucket")
		AWS_ACCESS_KEY_ID = credentials("docker-volume-backup-aws-access-key")
		AWS_SECRET_ACCESS_KEY = credentials("docker-volume-backup-aws-secret-key")
	}
  parameters {
		booleanParam(
			name: 'Deploy',
			defaultValue: false,
			description: 'Only deploy the service'
		)
		booleanParam(
			name: 'Update',
			defaultValue: false,
			description: 'Only update and restart the service'
		)
		booleanParam(
			name: 'Restart',
			defaultValue: false,
			description: 'Only restart the service'
		)
		booleanParam(
			name: 'Shutdown',
			defaultValue: false,
			description: 'Shutdown the service'
		)
		booleanParam(
			name: 'Nuke',
			defaultValue: false,
			description: 'Destroy containers, networks and volumes'
		)
	}
	stages {
		stage("Pull Pi-hole images") {
			when {
				expression {
					params.Deploy || params.Update
				}
			}
			steps {
				script {
					sh """
						cd $SERVICE
						docker compose pull
          """
				}
			}
		}
		stage("Deploy Pi-hole") {
			when {
				expression {
					params.Deploy || params.Update
				}
			}
			steps {
				script {
					sh """
						cd $SERVICE
						docker compose up -d --remove-orphans
          """
				}
			}
		}
		stage("Restart Pi-hole") {
			when {
				expression {
					params.Restart
				}
			}
			steps {
				script {
					sh """
						cd $SERVICE
						docker compose restart
          """
				}
			}
		}
		stage("Shutdown Pi-Hole stack") {
			when {
				expression {
					params.Shutdown
				}
			}
			steps {
				script {
					sh """
						cd $SERVICE
						docker compose down
          """
				}
			}
		}
		stage("Nuke Pi-Hole stack") {
			when {
				expression {
					params.Nuke
				}
			}
			steps {
				script {
					sh """
						cd $SERVICE
						docker compose down -v
          """
				}
			}
		}
	}
	post {
		always {
			cleanWs()
		}
	}
}
