version: '3.7'

volumes:
  vaultwarden_data:
    name: vaultwarden_data

networks:
  vaultwarden_net:
    name: vaultwarden_net

services:
  vaultwarden:
    image: vaultwarden/server:$VERSION
    container_name: vaultwarden
    volumes:
      - vaultwarden_data:/data/
    networks:
      - vaultwarden_net
    labels:
      - "diun.enable=true"
      - "docker-volume-backup.stop-during-backup=true"
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.rule=Host(`$VAULTWARDEN_DOMAIN`)"
      - "traefik.http.routers.vaultwarden.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden.tls=true"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
    restart: always

  vaultwarden_backup:
    image: jareware/docker-volume-backup:$DVB_VERSION
    container_name: vaultwarden_backup
    environment:
      AWS_S3_BUCKET_NAME: $AWS_S3_BUCKET_NAME
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      BACKUP_FILENAME: vaultwarden.tar.gz
    volumes:
      - vaultwarden_data:/backup/vaultwarden_data
      - $DOCKER_SOCKET:/var/run/docker.sock:ro
    labels:
      - "diun.enable=true"
    restart: always
