version: '3.7'

volumes:
  gitea_data:
    name: gitea_data
  gitea_db:
    name: gitea_db

networks:
  gitea_net:
    name: gitea_net

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    hostname: $GITEA_HOST_NAME
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea_db:5432
      - GITEA__database__NAME=$GITEA_DB
      - GITEA__database__USER=$GITEA_DB_USER
      - GITEA__database__PASSWD=$GITEA_DB_PASSWORD
    expose:
      - 3000
      - 22
    networks:
      - gitea_net
    labels:
      - "diun.enable=true"
      - "docker-volume-backup.stop-during-backup=true"
    restart: always
    depends_on:
      - gitea_db

  gitea_db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=$GITEA_DB_USER
      - POSTGRES_PASSWORD=$GITEA_DB_PASSWORD
      - POSTGRES_DB=$GITEA_DB
    networks:
      - gitea_net
    volumes:
      - gitea_db:/var/lib/postgresql/data

  gitea_backup:
    image: jareware/docker-volume-backup:$DVB_VERSION
    container_name: gitea_backup
    environment:
      AWS_S3_BUCKET_NAME: $AWS_S3_BUCKET_NAME
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      BACKUP_FILENAME: gitea.tar.gz
    volumes:
      - gitea_data:/backup/gitea_data
      - $DOCKER_SOCKET:/var/run/docker.sock:ro
    labels:
      - "diun.enable=true"
    restart: always

  gitea_db_backup:
    image: jareware/docker-volume-backup:$DVB_VERSION
    container_name: gitea_db_backup
    environment:
      AWS_S3_BUCKET_NAME: $AWS_S3_BUCKET_NAME
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      BACKUP_FILENAME: gitea_db.tar.gz
    volumes:
      - gitea_db:/backup/gitea_db
      - $DOCKER_SOCKET:/var/run/docker.sock:ro
    labels:
      - "diun.enable=true"
    restart: always
