version: '3.7'

networks:
  traefik_net:
    name: traefik_net

  2fauth_net:
    name: 2fauth_net
    external: true
  firezone_net:
    name: firezone_net
    external: true
  flame_net:
    name: flame_net
    external: true
  gitea_net:
    name: gitea_net
    external: true
  monitoring_net:
    name: monitoring_net
    external: true
  jenkins_net:
    name: jenkins_net
    external: true
  media_server_net:
    name: media_server_net
    external: true
  pi_hole_net:
    name: pi_hole_net
    external: true
  portainer_net:
    name: portainer_net
    external: true
  uptime_kuma_net:
    name: uptime_kuma_net
    external: true
  vaultwarden_net:
    name: vaultwarden_net
    external: true
  youtrack_net:
    name: youtrack_net
    external: true
  
volumes:
  certbot_certs:
    name: certbot_certs
    external: true

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--configFile=/etc/traefik/dynamic/traefik.yml"
    ports:
      - 443:443
      - 22:22
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker-container-config/traefik/traefik.yml:/etc/traefik/dynamic/traefik.yml:ro
      - /docker-container-config/traefik/tls-certs.toml:/etc/traefik/tls-certs.toml:ro
      - certbot_certs:/etc/traefik/certs:ro
    networks:
      - traefik_net
      - 2fauth_net
      - firezone_net
      - flame_net
      - gitea_net
      - monitoring_net
      - jenkins_net
      - media_server_net
      - pi_hole_net
      - portainer_net
      - uptime_kuma_net
      - vaultwarden_net
      - youtrack_net
    labels:
      - "diun.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.dash.rule=Host(`$TRAEFIK_DOMAIN`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dash.service=api@internal"
      - "traefik.http.routers.dash.entrypoints=websecure"
      - "traefik.http.routers.dash.tls=true"
      - "traefik.http.routers.dash.tls.domains[0].main=*.cjww.dev"
      - "traefik.http.routers.dash.tls.domains[0].sans=$TRAEFIK_DOMAIN"
    restart: always

  # traefik_backup:
  #   image: jareware/docker-volume-backup:$DVB_VERSION
  #   container_name: traefik_backup
  #   environment:
  #     AWS_S3_BUCKET_NAME: $AWS_S3_BUCKET_NAME
  #     AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  #     AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  #     BACKUP_FILENAME: traefik.tar.gz
  #   volumes:
  #     - certbot_certs:/backup/certbot_certs
  #     - $DOCKER_SOCKET:/var/run/docker.sock:ro
  #   labels:
  #     - "diun.enable=true"
  #   restart: always
