global:
  checkNewVersion: true
  sendAnonymousUsage: false  # true by default

# Log information
# ---
log:
  level: DEBUG  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: common  # common, json, logfmt
  # filePath: /var/log/traefik/traefik.log

# Accesslog
# ---
accesslog:
  format: common  # common, json, logfmt
  # filePath: /var/log/traefik/access.log

# Entry Points configuration
# ---
entryPoints:
  websecure:
    address: :443
    http:
      tls: true
  ssh:
    address: :22

# Providers configuration
# ---
providers:
  docker:
    exposedbydefault: false
    watch: true
  file:
    directory: /etc/traefik
    watch: true

# API configuration
# ---
api:
  dashboard: true
  insecure: false

# Overwrite Default Certificates
# ---
tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/live/cjww.dev/fullchain.pem
        keyFile: /etc/traefik/certs/live/cjww.dev/privkey.pem
