# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

# Traefik proxy
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.32.3

homeassistant:
  name: "9 OC"
  unit_system: metric
  currency: GBP
  internal_url: "DOMAIN"
  external_url: "DOMAIN"

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
