version: '3.7'

volumes:
  home_assistant_data:
    name: home_assistant_data

services:
  home_assistant:
    image: ghcr.io/home-assistant/home-assistant:$VERSION
    container_name: home_assistant
    hostname: $HOME_ASSISTANT_HOST_NAME
    volumes:
      - home_assistant_data:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    network_mode: host
    labels:
      - "diun.enable=true"
      - "docker-volume-backup.stop-during-backup=true"
    restart: always

  home_assistant_backup:
    image: jareware/docker-volume-backup:$DVB_VERSION
    container_name: home_assistant_backup
    environment:
      AWS_S3_BUCKET_NAME: $AWS_S3_BUCKET_NAME
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      BACKUP_FILENAME: home-assistant.tar.gz
    volumes:
      - home_assistant_data:/backup/home_assistant_data
      - $DOCKER_SOCKET:/var/run/docker.sock:ro
    labels:
      - "diun.enable=true"
    restart: always
