pipeline {
	agent {
		docker {
			image 'docker:latest'
			args '-v /var/run/docker.sock:/var/run/docker.sock'
		}
	}
	options {
		ansiColor('xterm')
	}
	environment {
    SERVICE = "diun"
    VERSION = "latest"
    TZ = "Europe/London"
    LOG_LEVEL = "info"
    LOG_JSON = true
    DIUN_WATCH_WORKERS = 20
    DIUN_WATCH_SCHEDULE = "0 */6 * * *"
    DIUN_PROVIDERS_DOCKER = true
    DOCKER_SOCKET = "/var/run/docker.sock"
    DIUN_HOST_NAME = credentials("diun-host-name")
    DIUN_NOTIF_SLACK_WEBHOOKURL = credentials("diun-slack-webhook")
    DIUN_WATCH_FIRSTCHECKNOTIF = true
		DIUN_NOTIF_WEBHOOK_ENDPOINT = credentials("diun-webhook")
		DIUN_NOTIF_WEBHOOK_METHOD = "POST"
	}
  parameters {
		booleanParam(
			name: 'Deploy',
			defaultValue: false,
			description: 'Only deploy the service'
		)
		booleanParam(
			name: 'Update',
			defaultValue: false,
			description: 'Only update and restart the service'
		)
		booleanParam(
			name: 'Restart',
			defaultValue: false,
			description: 'Only restart the service'
		)
		booleanParam(
			name: 'Shutdown',
			defaultValue: false,
			description: 'Shutdown the service'
		)
		booleanParam(
			name: 'Nuke',
			defaultValue: false,
			description: 'Destroy containers, networks and volumes'
		)
	}
	stages {
		stage("Pull Diun images") {
			when {
				expression {
					params.Deploy || params.Update
				}
			}
			steps {
				script {
					sh """
						cd $SERVICE
						docker compose pull
          """
				}
			}
		}
		stage("Deploy Diun") {
			when {
				expression {
					params.Deploy || params.Update
				}
			}
			steps {
				script {
					sh """
						cd $SERVICE
						docker compose up -d --remove-orphans
          """
				}
			}
		}
		stage("Restart Diun") {
			when {
				expression {
					params.Restart
				}
			}
			steps {
				script {
					sh """
						cd $SERVICE
						docker compose restart
          """
				}
			}
		}
		stage("Shutdown Diun stack") {
			when {
				expression {
					params.Shutdown
				}
			}
			steps {
				script {
					sh """
						cd $SERVICE
						docker compose down
          """
				}
			}
		}
		stage("Nuke Diun stack") {
			when {
				expression {
					params.Nuke
				}
			}
			steps {
				script {
					sh """
						cd $SERVICE
						docker compose down -v
          """
				}
			}
		}
	}
	post {
		always {
			cleanWs()
		}
	}
}
