version: '3.7'

volumes:
  prowlarr:
    name: prowlarr
  sonarr:
    name: sonarr
  radarr:
    name: radarr
  bazarr:
    name: bazarr
  transmission:
    name: transmission

networks:
  media_server_net:
    name: media_server_net

services:
  expressvpn:
    image: polkaned/expressvpn:$EXPRESS_VPN_VERSION
    container_name: expressvpn
    hostname: $EXPRESS_VPN_HOST_NAME
    environment:
      - ACTIVATION_CODE=$EXPRESS_VPN_ACTIVATION_CODE
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    privileged: true
    tty: true
    expose:
      - 8090
      - 6881
      - 6767
      - 8080
      - 9117
      - 8989
      - 7878
      - 8686
      - 9696
      - 9091
      - 51413
    # ports:
    #   # QBT UI Port
    #   - $INTERFACE_BIND:8090:8090
    #   # Bittorrent port
    #   - $INTERFACE_BIND:6881:6881
    #   - $INTERFACE_BIND:6881:6881/udp
    #   # Web port
    #   - $INTERFACE_BIND:8086:8080
    #   - $INTERFACE_BIND:9117:9117
    #   # Sonarr port
    #   - $INTERFACE_BIND:8989:8989
    #   # Radarr port
    #   - $INTERFACE_BIND:7878:7878
    #   # Lidarr port
    #   - $INTERFACE_BIND:8686:8686
    #   # Prowlarr port
    #   - $INTERFACE_BIND:9696:9696
    #   # Transmission
    #   - $INTERFACE_BIND:9091:9091
    #   - $INTERFACE_BIND:51413:51413
    #   - $INTERFACE_BIND:51413:51413/udp
    command: /bin/bash
    networks:
      - media_server_net
    labels:
      - "diun.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`$TRANSMISSION_DOMAIN`)"
      - "traefik.http.routers.transmission.entrypoints=websecure"
      - "traefik.http.routers.transmission.tls=true"
      - "traefik.http.routers.transmission.service=transmission"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"
      - "traefik.http.routers.prowlarr.rule=Host(`$PROWLARR_DOMAIN`)"
      - "traefik.http.routers.prowlarr.entrypoints=websecure"
      - "traefik.http.routers.prowlarr.tls=true"
      - "traefik.http.routers.prowlarr.service=prowlarr"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
      - "traefik.http.routers.sonarr.rule=Host(`$SONARR_DOMAIN`)"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.routers.sonarr.service=sonarr"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - "traefik.http.routers.radarr.rule=Host(`$RADARR_DOMAIN`)"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.routers.radarr.service=radarr"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
    restart: always

  transmission:
    #image: lscr.io/linuxserver/transmission:$TRANSMISSION_VERSION
    image: lscr.io/linuxserver/transmission:3.00-r8-ls149
    container_name: transmission
    environment:
      - PUID=$USER_ID
      - PGID=$GROUP_ID
      - TZ=$TZ
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - USER=$TRANSMISSION_USERNAME
      - PASS=$TRANSMISSION_PASSWORD
    volumes:
      - transmission:/config
      - $DOWNLOAD_PATH:/downloads
    # Route egress traffic through VPN container
    network_mode: service:expressvpn
    labels:
      - "diun.enable=true"
      - "docker-volume-backup.stop-during-backup=true"
    restart: always

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:$PROWLARR_VERSION
    container_name: prowlarr
    environment:
      - PUID=$USER_ID
      - PGID=$GROUP_ID
      - TZ=$TZ
    volumes:
      - prowlarr:/config
    # Route egress traffic through VPN container
    network_mode: service:expressvpn
    labels:
      - "diun.enable=true"
      - "docker-volume-backup.stop-during-backup=true"
    restart: always

  sonarr:
    image: lscr.io/linuxserver/sonarr:$SONARR_VERSION
    container_name: sonarr
    environment:
      - PUID=$USER_ID
      - PGID=$GROUP_ID
      - TZ=$TZ
    volumes:
      - sonarr:/config
      - $MEDIA_PATH/tv:/tv
      - $DOWNLOAD_PATH:/downloads #optional
    # Route egress traffic through VPN container
    network_mode: service:expressvpn
    labels:
      - "diun.enable=true"
      - "docker-volume-backup.stop-during-backup=true"
    restart: always

  radarr:
    image: lscr.io/linuxserver/radarr:$RADARR_VERSION
    container_name: radarr
    environment:
      - PUID=$USER_ID
      - PGID=$GROUP_ID
      - TZ=$TZ
    volumes:
      - radarr:/config
      - $MEDIA_PATH/movies:/movies
      - $DOWNLOAD_PATH:/downloads
    # Route egress traffic through VPN container
    network_mode: service:expressvpn
    labels:
      - "diun.enable=true"
      - "docker-volume-backup.stop-during-backup=true"
    restart: always

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=$USER_ID
      - PGID=$GROUP_ID
      - TZ=$TZ
    volumes:
      - bazarr:/config
      - $MEDIA_PATH/movies:/movies
      - $MEDIA_PATH/tv:/tv
    network_mode: service:expressvpn
    labels:
      - "diun.enable=true"
      - "docker-volume-backup.stop-during-backup=true"
    restart: always

  plex-media-server:
    image: lscr.io/linuxserver/plex:$PLEX_VERSION
    container_name: plex
    environment:
      - PUID=$USER_ID
      - PGID=$GROUP_ID
      - VERSION=docker
      - name=$PLEX_CLAIM
      - PLEX_CLAIM=$PLEX_CLAIM
      - ADVERTISE_IP=http://$HOST_IP:32400,https://$PLEX_DOMAIN:443
    volumes:
      - $MEDIA_PATH/tv:/plex-media/tv
      - $MEDIA_PATH/movies:/plex-media/movies
      - $MEDIA_PATH/photos:/plex-media/photos
    network_mode: host
    labels:
      - "diun.enable=true"
    restart: always

  pihole_backup:
    image: jareware/docker-volume-backup:$DVB_VERSION
    container_name: media_server_backup
    environment:
      AWS_S3_BUCKET_NAME: $AWS_S3_BUCKET_NAME
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      BACKUP_FILENAME: pihole.tar.gz
    volumes:
      - transmission:/backup/transmission
      - prowlarr:/backup/prowlarr
      - sonarr:/backup/sonarr
      - radarr:/backup/radarr
      - bazarr:/backup/bazarr
      - $DOCKER_SOCKET:/var/run/docker.sock:ro
    labels:
      - "diun.enable=true"
    restart: always
