version: '3.7'

networks:
  nginx_net:
    name: nginx_net

  media_server_net:
    name: media_server_net
    external: true
  # 2fauth_net:
  #   name: 2fauth_net
  #   external: true
  flame_net:
    name: flame_net
    external: true
  monitoring_net:
    name: monitoring_net
    external: true
  pi_hole_net:
    name: pi_hole_net
    external: true
  portainer_net:
    name: portainer_net
    external: true
  # vaultwarden_net:
  #   name: vaultwarden_net
  #   external: true

volumes:
  certbot_certs:
    name: certbot_certs

services:
  nginx:
    image: nginx:$NGINX_TAG
    container_name: $NGINX_CONTAINER_NAME
    hostname: $NGINX_HOST_NAME
    ports:
      - $HTTP_INTERFACE_BIND:443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot_certs:/etc/nginx/ssl/:ro
    networks:
      - nginx_net
      - media_server_net
      # - 2fauth_net
      # - flame_net
      - monitoring_net
      - pi_hole_net
      - portainer_net
      # - vaultwarden_net
    labels:
      - "diun.enable=true"
    restart: always

  certbot:
    image: certbot/certbot:latest
    container_name: $CERTBOT_CONTAINER_NAME
    hostname: $CERTBOT_HOST_NAME
    volumes:
      - certbot_certs:/etc/letsencrypt/:rw
    labels:
      - "diun.enable=true"

  nginx_ssl_backup:
    image: jareware/docker-volume-backup:$DVB_TAG
    container_name: $DVB_CONTAINER_NAME
    hostname: $DVB_HOST_NAME
    environment:
      AWS_S3_BUCKET_NAME: $AWS_S3_BUCKET_NAME
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      BACKUP_FILENAME: nginx-ssl.tar.gz
    volumes:
      - certbot_certs:/backup/certbot_certs
      - $DOCKER_SOCKET:/var/run/docker.sock:ro
    labels:
      - "diun.enable=true"
    restart: always
