version: '3.7'

networks:
  jenkins_net:
    name: jenkins_net

volumes:
  jenkins_home:
    name: jenkins_home
  jenkins_docker_certs:
    name: jenkins_docker_certs

services:
  jenkins:
    build:
      context: .
      args:
        JENKINS_TAG: $JENKINS_VERSION
    container_name: jenkins
    hostname: $JENKINS_HOST
    privileged: true
    expose:
      - 8080
    user: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - $DOCKER_SOCKET:/var/run/docker.sock
      - /docker-container-config:/docker-container-config
    networks:
      - jenkins_net
    labels:
      - "diun.enable=true"
      - "docker-volume-backup.stop-during-backup=true"
    restart: always

  jenkins_backup:
    image: jareware/docker-volume-backup:$DVB_VERSION
    container_name: jenkins_backup
    environment:
      AWS_S3_BUCKET_NAME: $AWS_S3_BUCKET_NAME
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      BACKUP_FILENAME: jenkins.tar.gz
    volumes:
      - jenkins_home:/backup/jenkins_home
      - $DOCKER_SOCKET:/var/run/docker.sock:ro
    labels:
      - "diun.enable=true"
    restart: always