pipeline {
	agent {
		docker {
			image 'docker:latest'
			args '-v /var/run/docker.sock:/var/run/docker.sock'
		}
	}
	options {
		ansiColor('xterm')
	}
	environment {
    SERVICE = "firezone-wireguard"
    VERSION = "2.3.0"
    
		FIREZONE_HOST_NAME = credentials("firezone-host-name")
		VPN_HOST_NAME = credentials("vpn-host-name")
		ADMIN_EMAIL = credentials("firezone-admin-email")
		ADMIN_PASSWORD = credentials("firezone-admin-password")
		GUARDIAN_SECRET_KEY = credentials("firezone-guardian-secret-key")
		SECRET_KEY_BASE = credentials("firezone-secret-key-base")
		LIVE_VIEW_SIGNING_SALT = credentials("firezone-live-view-signing-salt")
		COOKIE_SIGNING_SALT = credentials("firezone-cookie-signing-salt")
		COOKIE_ENCRYPTION_SALT = credentials("firezone-cookie-encryption-salt")
		DATABASE_ENCRYPTION_KEY = credentials("firezone-database-encryption-key")

		POSTGRES_DB = "firezone"
		POSTGRES_USER = credentials("firezone-db-user")
		POSTGRES_PASSWORD = credentials("firezone-db-password")
		POSTGRES_HOST_NAME = credentials("firezone-postgres-host-name")

		DVB_VERSION = "2.6.0"
		DOCKER_SOCKET = "/var/run/docker.sock"
		AWS_S3_BUCKET_NAME = credentials("docker-volume-backup-bucket")
		AWS_ACCESS_KEY_ID = credentials("docker-volume-backup-aws-access-key")
		AWS_SECRET_ACCESS_KEY = credentials("docker-volume-backup-aws-secret-key")
	}
  parameters {
		booleanParam(
			name: 'Deploy',
			defaultValue: false,
			description: 'Only deploy the service'
		)
		booleanParam(
			name: 'Update',
			defaultValue: false,
			description: 'Only update and restart the service'
		)
		booleanParam(
			name: 'Restart',
			defaultValue: false,
			description: 'Only restart the service'
		)
	}
	stages {
		stage("Pull Firezone images") {
			when {
				expression {
					params.Deploy || params.Update
				}
			}
			steps {
				script {
					sh """
						cd $SERVICE
						docker compose pull
          """
				}
			}
		}
		stage("Deploy Firezone") {
			when {
				expression {
					params.Deploy || params.Update
				}
			}
			steps {
				script {
					sh """
						cd $SERVICE
						docker compose up -d --remove-orphans
          """
				}
			}
		}
		stage("Restart Firezone") {
			when {
				expression {
					params.Restart
				}
			}
			steps {
				script {
					sh """
						cd $SERVICE
						docker compose restart
          """
				}
			}
		}
	}
	post {
		always {
			cleanWs()
		}
	}
}
