version: '3.7'

volumes:
  portainer_data:
    name: portainer_data

networks:
  portainer_net:
    name: portainer_net

services:
  portainer:
    image: portainer/portainer-ce:$VERSION
    container_name: portainer
    security_opt:
      - no-new-privileges:true
    volumes:
      - portainer_data:/data
      - $DOCKER_SOCKET:/var/run/docker.sock
      - $LOCALTIME_PATH:/etc/localtime:ro
    networks:
      - portainer_net
    labels:
      - "diun.enable=true"
      - "docker-volume-backup.stop-during-backup=true"
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`$PORTAINER_DOMAIN`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    restart: always

  portainer_backup:
    image: jareware/docker-volume-backup:$DVB_VERSION
    container_name: portainer_backup
    environment:
      AWS_S3_BUCKET_NAME: $AWS_S3_BUCKET_NAME
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      BACKUP_FILENAME: portainer.tar.gz
    volumes:
      - portainer_data:/backup/portainer_data
      - $DOCKER_SOCKET:/var/run/docker.sock:ro
    labels:
      - "diun.enable=true"
    restart: always
    