version: '3.7'

volumes:
  portainer_data:
    name: portainer_data

networks:
  portainer_net:
    name: portainer_net

services:
  portainer:
    image: portainer/portainer-ce:$TAG
    container_name: portainer
    hostname: $PORTAINER_HOST_NAME
    security_opt:
      - no-new-privileges:true
    #TODO: env vars for authentications and e
    ports:
      - $INTERFACE_BIND:9000:9000
    volumes:
      - portainer_data:/data
      - $DOCKER_SOCKET:/var/run/docker.sock
      - $LOCALTIME_PATH:/etc/localtime:ro
    networks:
      - portainer_net
    labels:
      - "diun.enable=true"
    restart: always

  portainer_backup:
    image: jareware/docker-volume-backup:$DVB_TAG
    container_name: $DVB_CONTAINER_NAME
    hostname: $DVB_HOST_NAME
    environment:
      AWS_S3_BUCKET_NAME: $AWS_S3_BUCKET_NAME
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      BACKUP_FILENAME: portainer.tar.gz
    volumes:
      - portainer_data:/backup/portainer_data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "diun.enable=true"
      - "docker-volume-backup.stop-during-backup=true"
    restart: always