version: '3.7'

volumes:
  portainer_data:
    name: portainer_data

networks:
  portainer_net:
    name: portainer_net

services:
  portainer:
    image: portainer/portainer-ce:$VERSION
    container_name: portainer
    hostname: $PORTAINER_HOST_NAME
    security_opt:
      - no-new-privileges:true
    expose:
      - 9000
    volumes:
      - portainer_data:/data
      - $DOCKER_SOCKET:/var/run/docker.sock
      - $LOCALTIME_PATH:/etc/localtime:ro
    networks:
      - portainer_net
    labels:
      - "diun.enable=true"
      - "docker-volume-backup.stop-during-backup=true"
    restart: always
