pipeline {
	agent {
		docker {
			image 'docker:latest'
			args '-v /var/run/docker.sock:/var/run/docker.sock'
		}
	}
	options {
		ansiColor('xterm')
	}
	environment {
		SERVICE = "portainer"
		VERSION = "linux-amd64"
		DVB_VERSION = "2.6.0"
		DOCKER_SOCKET = "/var/run/docker.sock"
		LOCALTIME_PATH = "/etc/localtime"
		PORTAINER_DOMAIN = credentials("portainer-domain")
		AWS_S3_BUCKET_NAME = credentials("docker-volume-backup-bucket")
		AWS_ACCESS_KEY_ID = credentials("docker-volume-backup-aws-access-key")
		AWS_SECRET_ACCESS_KEY = credentials("docker-volume-backup-aws-secret-key")
	}
  parameters {
		booleanParam(
			name: 'Deploy',
			defaultValue: false,
			description: 'Only deploy the service'
		)
		booleanParam(
			name: 'Update',
			defaultValue: false,
			description: 'Only update and restart the service'
		)
		booleanParam(
			name: 'Restart',
			defaultValue: false,
			description: 'Only restart the service'
		)
	}
	stages {
		stage("Pull Portainer images") {
			when {
				expression {
					params.Deploy || params.Update
				}
			}
			steps {
				script {
					sh """
						cd $SERVICE
						docker compose pull
          """
				}
			}
		}
		stage("Deploy Portainer") {
			when {
				expression {
					params.Deploy || params.Update
				}
			}
			steps {
				script {
					sh """
						cd $SERVICE
						docker compose up -d --remove-orphans
          """
				}
			}
		}
		stage("Restart Portainer") {
			when {
				expression {
					params.Restart
				}
			}
			steps {
				script {
					sh """
						cd $SERVICE
						docker compose restart --remove-orphans
          """
				}
			}
		}
	}
	post {
		always {
			cleanWs()
		}
	}
}
